title: 城乡居民基本医疗保险
author: Mr.Hope
time: 2022年6月27日
shareable: true
content:
  - tag: text
    text:
      - 学校每年都会组织学生办理“长春市城乡居民基本医疗保险”。

  - tag: text
    type: info
    heading: 城镇居民基本医疗保险
    text: 城镇居民基本医疗保险是社会医疗保险的组成部分，采取以政府为主导，以居民个人 (家庭) 缴费为主，政府适度补助为辅的筹资方式，按照缴费标准和待遇水平相一致的原则，为城镇居民提供医疗需求的医疗保险制度。

  - tag: text
    type: tip
    text:
      - 入校前已缴纳的城乡居民基本医疗保险的结束时间为入学年底，所以无需担心保险的断缴问题。
      - 所以学校在 10 月后才会开展保险的统计、信息录入和收缴工作。

  - tag: text
    type: info
    heading: 缴纳地点
    text:
      - 参保学生需拥有教育部门登记在册的学籍。
      - 吉林省范围内的全日制在籍学生统一在学籍地参保。
      - 在籍学生为经省内各地县 (市、区)级民政或乡村振兴部门认定的符合参保资助条件的困难人员可选择在身仹认定地参保缴费，直接享受参保地相关的待遇政策。如选择在居住地或学籍地参保，按普通居民或学生身份享受参保地相关待遇，其参保资劣及直接医疗救劣等保障待遇到身份认定地医保部门申请享受。
      - 若参保学生为省外民政或乡村振兴部门认定的符合参保资助条件的困难人员 ，可选择在认定地参保，享受参保地相关待遇政策；如选择在学籍地 (吉林省内) 参保，全额缴纳年度个人医保费后，可享受吉林省普通居民 (学生) 医保待遇。

  - tag: title
    text: 信息录入

  - tag: p
    text:
      - 保险信息录入由各辅导员负责，通过学校与医保局进行联系，将学生保险经办机构改为“长春市市本级社会医疗保险管理局”。

  - tag: title
    text: 缴费标准

  - tag: text
    type: info
    heading: 2022年度收费标准
    text:
      - 230 元/人/年

  - tag: text
    type: note
    heading: 困难学生
    text:
      - 由长春市相关部门认定的符合参保资助条件的困难学生城镇居民基本医疗保险个人缴纳标准为 100 元 (享受 130 元资助)。

  - tag: title
    text: 城乡居民医保缴费方式与时间

  - tag: text
    text:
      - 请关注辅导员的通知，并在通知规定的时间内完成缴费。
      - 缴费通过“吉林税务社保缴费”小程序进行缴费。

  - tag: card
    title: 城乡居民医保缴费
    options:
      appId: wx2bd3e1deb552a91c
      path: pages/index/index

  - tag: img
    src: $img/check/insurance-base-pay.jpg
    env:
      - qq

  - tag: ul
    type: warning
    heading: 缴费前确认
    text:
      - 自己的保险经办机构为“长春市市本级社会医疗保险管理局”
      - 自己的保险费用为 230 元

  - tag: title
    text: 保险生效时间

  - tag: ul
    heading: 2022年度城乡居民基本医疗保险
    text:
      - 在集中预缴费期内缴纳个人医保费的参保人员 (含新参保人员) ，享受2022年1月1日至2022年12月31日一个自然年度的医保待遇。
      - 在集中预缴费期外补缴个人医保费的参保人员 (含新参保人员) ，医保部门将设置3个月的等待期，等待期内不享受医保待遇。

  - tag: title
    text: 保险报销

  - tag: text
    type: info
    heading: 请参见长春市城乡居民基本医疗保险报销
    path: reimburse

  - tag: title
    text: 常见问题

  - tag: ul
    type: info
    heading: 缴费程序时显示经办机构为其他城市
    text:
      - 若已经在所在地完成缴费，那么享受的就是经办机构显示的地区的医保政策。如果想在2022年享受长春市的大学生医保待遇，就需要先到当地办理停保退费后，联系辅导员在参保平台录入“学生新参保”信息，待缴费程序上参保信息、金额、经办机构均正确，再完成缴费。
      - 若未进行任何缴费，请联系辅导员在参保平台做“学生参保身仹变更”处理，等缴费程序上参保信息、金额、经办机构均正确后，直接缴费。

  - tag: text
    type: info
    heading: 不同人员的缴费金额
    text:
      - 城乡居民成年人个人缴纳370 元
      - 大中小学生及十八周岁以下人员个人缴纳 230 元
      - 城乡低保对象等由相关部门认定的符合政策的困难人员成年人个人缴纳 240 元
      - 城乡低保对象等由相关部门认定的符合政策的困难人员大中小学生及十八周岁以下人员个人缴纳 100 元
      - 城乡特困人员个人缴纳 10 元

  - tag: text
    type: info
    heading: 如果缴费程序上显示金额不学生实际应缴纳金额不一样怎么办?
    text:
      - 长春市市本级城乡低保对象等由相关部门认定的符合政策的困难学生，本应该缴纳 100 元医保费用，如缴费程序上显示230元或 370 元，请进行以下操作。
      - 首先联系辅导员，要求辅导员确认参保身份。
      - 之后由学生本人或家长携带户口本、低保证等相关部门认证的证件、代办人身份证或本人身份证到繁荣路医保局进行相应困难人员身份标识。外六县城乡低保对象等由相关部门认定的符合政策的困难学生可联系当地医保局咨询如何办理。
