title: 火车优惠卡申领
author: Mr.Hope
time: 2022 年 8 月 9 日
shareable: true
content:
  - tag: title
    text: 办理方式

  - tag: text
    text:
      - 在注册学籍时，系统会要求学生填写居住地和火车优惠区间，学校会以此为依据批量为新生申办火车优惠磁条。

  - tag: title
    text: 价格

  - tag: text
    text:
      - 火车优惠磁条办理时收取工本费 7 元，如有不需要的同学，须在统一办理前主动提出。
      - 如果火车优惠磁条丢失，需要补办，同样收取工本费 7 元。

  - tag: title
    text: 火车优惠磁条使用方式

  - tag: list
    header: false
    items:
      - text: 火车学生票
        icon: train
        path: /guide/traffic/train/student/
