name: Deploy resource to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: main
          fetch-depth: 0

      - uses: actions/cache@v2.1.6
        id: node-modules
        with:
          path: node_modules/
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Deps
        if: steps.node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - name: Config environment
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.INFO_TSCONTENT }}" > ./scripts/info.ts
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan mp.innenu.com >> ~/.ssh/known_hosts
          git config --global user.name 'Mr.Hope'
          git config --global user.email 'zhangbowang1998@gmail.com'

        # mkdir service/info
        # echo '${{ secrets.APPID_SECRET }}' > service/info/appid.php

      - name: lint
        run: yarn run lint

      - name: Deploy
        run: |
          git push -f git@mp.innenu.com:/www/wwwroot/mp main
          ssh git@mp.innenu.com "cd /www/wwwroot/mp && git reset --hard HEAD"
        # yarn run upload
